// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DayOfWeek.proto

public final class DayOfWeekOuterClass {
  private DayOfWeekOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DayOfWeek}
   */
  public enum DayOfWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DAY_OF_WEEK_UNSPECIFIED = 0;</code>
     */
    DAY_OF_WEEK_UNSPECIFIED(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURDAY = 4;</code>
     */
    THURDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    /**
     * <code>SUNDAY = 7;</code>
     */
    SUNDAY(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DAY_OF_WEEK_UNSPECIFIED = 0;</code>
     */
    public static final int DAY_OF_WEEK_UNSPECIFIED_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURDAY = 4;</code>
     */
    public static final int THURDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;
    /**
     * <code>SUNDAY = 7;</code>
     */
    public static final int SUNDAY_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfWeek valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DayOfWeek forNumber(int value) {
      switch (value) {
        case 0: return DAY_OF_WEEK_UNSPECIFIED;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        case 7: return SUNDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>() {
            public DayOfWeek findValueByNumber(int number) {
              return DayOfWeek.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DayOfWeekOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final DayOfWeek[] VALUES = values();

    public static DayOfWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DayOfWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DayOfWeek)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017DayOfWeek.proto*\203\001\n\tDayOfWeek\022\033\n\027DAY_O" +
      "F_WEEK_UNSPECIFIED\020\000\022\n\n\006MONDAY\020\001\022\013\n\007TUES" +
      "DAY\020\002\022\r\n\tWEDNESDAY\020\003\022\013\n\007THURDAY\020\004\022\n\n\006FRI" +
      "DAY\020\005\022\014\n\010SATURDAY\020\006\022\n\n\006SUNDAY\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
